//
// Created by Jamie Cotter on 26/05/2023.
//

#ifndef CONTROLLER_REQUESTSIZES_H
#define CONTROLLER_REQUESTSIZES_H

#define LOW_TASK_SIZE 700
#define HIGH_TASK_SIZE 2250
#define STATE_UPDATE_SIZE 550
#define HALT_REQ_SIZE 550
#define TASK_FORWARD_SIZE 21500

#endif //CONTROLLER_REQUESTSIZES_H
