//
// Created by jamiec on 9/23/22.
//

#ifndef CONTROLLER_REQUESTTYPES_H
#define CONTROLLER_REQUESTTYPES_H

namespace constant {

#define SILENT_TASK_REMOVE 1
#define REQ_TYPE_STATE_UPDATE 2
#define PRUNE_DNN 3
#define HALT_REQ 4
#define DAG_DISRUPTION 5
#define LOW_COMPLEXITY 6
#define HIGH_COMPLEXITY 7
#define HIGH_WORK_REQUEST 8

}
#endif //CONTROLLER_REQUESTTYPES_H
