//
// Created by jamiec on 9/23/22.
//

#ifndef CONTROLLER_REQUESTTYPES_H
#define CONTROLLER_REQUESTTYPES_H

namespace constant {

#define REQ_TYPE_STATE_UPDATE 1
#define REGENERATE_DATA_STRUCTURE 2
#define BANDWIDTH_UPDATE_ITEM 3
#define NETWORK_DISC_UPDATE 4
#define HALT_REQ 6
#define LOW_COMPLEXITY 7
#define HIGH_COMPLEXITY 8


}
#endif //CONTROLLER_REQUESTTYPES_H
