//
// Created by Jamie Cotter on 13/02/2023.
//

#ifndef CONTROLLER_LOGTYPES_H
#define CONTROLLER_LOGTYPES_H

namespace enums {

    enum class LogTypeEnum : int {
        LOW_COMP_REQUEST = 0,
        HIGH_COMP_REQUEST = 1,
        DEVICE_REGISTER = 2,
        IPERF_RESULTS = 3,
        DAG_DISRUPTION_REQUEST = 4,
        STATE_UPDATE_REQUEST = 5,
        HIGH_COMP_FINISH = 6,
        DNN_PRUNE = 7,
        LOW_COMP_ALLOCATION_FAIL = 8,
        LOW_COMP_ALLOCATION_SUCCESS = 9,
        HALT_REQUEST = 10,
        HIGH_COMP_ALLOCATION_CORE_FAIL = 11,
        HIGH_COMP_ALLOCATION_SUCCESS = 12,
        HIGH_COMP_ALLOCATION_FAIL = 13,
        HIGH_COMP_REALLOCATION_FAIL = 14,
        DAG_DISRUPTION_SUCCESS = 15,
        DAG_DISRUPTION_FAIL = 17,
        HALT_DNN = 18,
        ADD_WORK_TASK = 19,
        EXPERIMENT_INITIALISE = 20,
        OUTBOUND_STATE_UPDATE = 21,
        OUTBOUND_TASK_ALLOCATION_HIGH = 22,
        OUTBOUND_TASK_REALLOCATION_HIGH = 23,
        OUTBOUND_HALT_REQUEST = 24,
        OUTBOUND_LOW_COMP_ALLOCATION = 25,
        ADD_NETWORK_TASK = 26,
        HIGH_COMP_REALLOCATION_SUCCESS = 27,



    };

} // model

#endif //CONTROLLER_LOGTYPES_H
