//
// Created by Jamie Cotter on 13/02/2023.
//

#ifndef CONTROLLER_LOGTYPES_H
#define CONTROLLER_LOGTYPES_H

namespace enums {

    enum class LogTypeEnum : int {
        LOW_COMP_REQUEST = 0,
        HIGH_COMP_REQUEST = 1,
        DEVICE_REGISTER = 2,
        IPERF_RESULTS = 3,
        DAG_DISRUPTION_REQUEST = 4,
        STATE_UPDATE_REQUEST = 5,
        HIGH_COMP_FINISH = 6,
        LOW_COMP_ALLOCATION_FAIL = 8,
        LOW_COMP_ALLOCATION_SUCCESS = 9,
        LOW_COMP_PREMPT_ALLOCATION_SUCCESS = 10,
        LOW_COMP_FINISH = 11,
        HALT_REQUEST = 12,
        HIGH_COMP_ALLOCATION_CORE_FAIL = 13,
        HIGH_COMP_ALLOCATION_SUCCESS = 14,
        HIGH_COMP_ALLOCATION_FAIL = 15,
        HIGH_COMP_REALLOCATION_FAIL = 16,
        DAG_DISRUPTION_SUCCESS = 17,
        DAG_DISRUPTION_FAIL = 18,
        HALT_DNN = 19,
        ADD_WORK_TASK = 20,
        EXPERIMENT_INITIALISE = 21,
        OUTBOUND_STATE_UPDATE = 22,
        OUTBOUND_TASK_ALLOCATION_HIGH = 23,
        OUTBOUND_TASK_REALLOCATION_HIGH = 24,
        OUTBOUND_HALT_REQUEST = 25,
        OUTBOUND_LOW_COMP_ALLOCATION = 26,
        ADD_NETWORK_TASK = 27,
        HIGH_COMP_REALLOCATION_SUCCESS = 28,
        VIOLATED_DEADLINE = 29,
        VIOLATED_DEADLINE_REQUEST = 30,
        BANDWIDTH_UPDATE_LOG = 31,
        BANDWIDTH_NEW_VALUE = 32,
        NEW_BUCKET_LINK = 33,
        OUTBOUND_COMMS_TEST = 34,
        LOW_COMP_PREEMPTION = 35
    };

} // model

#endif //CONTROLLER_LOGTYPES_H
